//! UniFFI echo scaffold: the exact Rust surface the UDL exposes.
//!
//! The binding talks to the core ONLY through `CoreBackend`, implemented for
//! the ubm-core-backed [`core_backend::CoreSession`] (one implementation;
//! contract truth is single-owned by `ubm-core`). Failures cross as result
//! records carrying the frozen C-UBM wire form — see the UDL header note.
//!
//! The former test-only `panic_probe` was deleted by the wiring slice:
//! probes must not ship in production paths. Containment at the generated
//! boundary rests on `uniffi_core::ffi::rustcalls::rust_call`
//! (`catch_unwind` at the pinned version).

// Allowed: generated scaffolding (`ubm_echo.uniffi.rs`, included below)
// defines a large metadata const that trips `large_const_arrays`. The lint
// fires only on generated code; nothing else in this crate is affected.
#![allow(clippy::large_const_arrays)]

mod core_backend;
mod mobile;

/// PR210-18 build identity constants and `ubm_build_identity_json`,
/// generated by `build.rs` from `bindings/ubm_build_identity.rs`.
pub mod build_identity {
    include!(concat!(env!("OUT_DIR"), "/ubm_build_identity.rs"));
}

use core_backend::{CoreSession, EchoError, SharedCore, StagedError};
// The mobile owner's UDL types must be nameable at the crate root for the
// generated scaffolding.
pub use mobile::{
    mobile_build_identity_json, mobile_contract_revision, mobile_host_current, mobile_host_install,
    mobile_wire_revision, MobileAdapterSnapshot, MobileAdvertisement, MobileCloseFailure,
    MobileCoreError, MobileCoreHost, MobileCoreSession, MobileGattCharacteristic,
    MobileGattDescriptor, MobileGattProperties, MobileGattService, MobileInstance,
    MobileInvokeCompletion, MobileManufacturerData, MobilePeerName, MobilePlatformRadio,
    MobileRadioCompletion, MobileRadioIngress, MobileRadioRequest, MobileRestoredPeer,
    MobileSecurityState, MobileServiceData, MobileWakeSink,
};

uniffi::include_scaffolding!("ubm_echo");

/// Mirrors UDL `dictionary EchoBytesResult` (converters generated from UDL).
pub struct EchoBytesResult {
    pub ok: bool,
    pub data: Vec<u8>,
    pub code: String,
    pub domain: String,
    pub operation: String,
}

/// Mirrors UDL `dictionary EchoCounterResult` (converters generated from UDL).
pub struct EchoCounterResult {
    pub ok: bool,
    pub value: String,
    pub code: String,
    pub domain: String,
    pub operation: String,
}

/// Mirrors UDL `dictionary EchoStatus` (converters generated from UDL).
pub struct EchoStatus {
    pub ok: bool,
    pub code: String,
    pub domain: String,
    pub operation: String,
}

fn ok_bytes(data: Vec<u8>) -> EchoBytesResult {
    EchoBytesResult {
        ok: true,
        data,
        code: String::new(),
        domain: String::new(),
        operation: String::new(),
    }
}

fn err_bytes(err: EchoError) -> EchoBytesResult {
    EchoBytesResult {
        ok: false,
        data: Vec::new(),
        code: err.code.to_string(),
        domain: err.domain.to_string(),
        operation: err.operation.to_string(),
    }
}

fn ok_counter(value: String) -> EchoCounterResult {
    EchoCounterResult {
        ok: true,
        value,
        code: String::new(),
        domain: String::new(),
        operation: String::new(),
    }
}

fn err_counter(err: EchoError) -> EchoCounterResult {
    EchoCounterResult {
        ok: false,
        value: String::new(),
        code: err.code.to_string(),
        domain: err.domain.to_string(),
        operation: err.operation.to_string(),
    }
}

fn err_counter_staged(err: StagedError) -> EchoCounterResult {
    EchoCounterResult {
        ok: false,
        value: String::new(),
        code: err.code().to_string(),
        domain: err.domain().to_string(),
        operation: err.operation().to_string(),
    }
}

fn ok_status() -> EchoStatus {
    EchoStatus {
        ok: true,
        code: String::new(),
        domain: String::new(),
        operation: String::new(),
    }
}

fn err_status(err: EchoError) -> EchoStatus {
    EchoStatus {
        ok: false,
        code: err.code.to_string(),
        domain: err.domain.to_string(),
        operation: err.operation.to_string(),
    }
}

/// Mirrors UDL `interface EchoSession` (scaffolding generated from UDL).
pub struct EchoSession {
    inner: SharedCore,
}

impl EchoSession {
    /// Opens a session. Never fails at construction: the revision gate runs
    /// on every method instead, so a foreign revision fails closed with
    /// `protocol.incompatible` on every call (no effect without valid init).
    pub fn new(revision: String) -> Self {
        Self {
            inner: CoreSession::open(&revision).into_shared(),
        }
    }

    pub fn echo_bytes(&self, input: Vec<u8>) -> EchoBytesResult {
        match self.inner.echo_bytes(&input) {
            Ok(data) => ok_bytes(data),
            Err(err) => err_bytes(err),
        }
    }

    pub fn echo_counter(&self, decimal: String) -> EchoCounterResult {
        match self.inner.echo_counter(&decimal) {
            Ok(value) => ok_counter(value),
            Err(err) => err_counter(err),
        }
    }

    pub fn echo_bytes_chunked(&self, input: Vec<u8>, chunks: u32) -> EchoBytesResult {
        match self.inner.echo_bytes_chunked(&input, chunks) {
            Ok(data) => ok_bytes(data),
            Err(err) => err_bytes(err),
        }
    }

    pub fn cancel_inflight(&self) -> EchoStatus {
        match self.inner.cancel_inflight() {
            Ok(()) => ok_status(),
            Err(err) => err_status(err),
        }
    }

    pub fn close(&self) -> EchoStatus {
        match self.inner.close() {
            Ok(()) => ok_status(),
            Err(err) => err_status(err),
        }
    }

    /// U7: observes the session-owned REAL Central (frozen revision plus
    /// live kernel counters as JSON, carried in `value`).
    pub fn central_status(&self) -> EchoCounterResult {
        match self.inner.central_status() {
            Ok(json) => ok_counter(json),
            Err(err) => err_counter(err),
        }
    }

    /// U7: drives a real kernel expiry sweep at decimal-string host time;
    /// the settled-operation count decimal travels in `value`.
    pub fn drive_expire_sweep(&self, now_ms: String) -> EchoCounterResult {
        match self.inner.drive_expire_sweep(&now_ms) {
            Ok(settled) => ok_counter(settled),
            Err(err) => err_counter(err),
        }
    }

    /// U7: drives the real shutdown transition; `released` /
    /// `release-failed` travels in `value`. Idempotent.
    pub fn drive_destroy(&self) -> EchoCounterResult {
        match self.inner.drive_destroy() {
            Ok(state) => ok_counter(state.to_string()),
            Err(err) => err_counter(err),
        }
    }

    /// U7 loud rejection for BLE transitions beyond the driven slice:
    /// `capability.unsupported|capability` in the status record, never
    /// silent or faked.
    pub fn request_ble_transition(&self, transition: String) -> EchoStatus {
        match self.inner.request_ble_transition(&transition) {
            Ok(()) => ok_status(),
            Err(err) => err_status(err),
        }
    }

    /// U7 staged-transition slice: runs one scripted synthetic-radio step
    /// (a JSON object line) and carries one JSON observation object in
    /// `value`. Step-level core rejections come back as data
    /// (`{"ok":false,...}` with the frozen wire identity); only the session
    /// lifetime fails the record.
    pub fn staged_step(&self, line: String) -> EchoCounterResult {
        match self.inner.staged_step(&line) {
            Ok(observation) => ok_counter(observation),
            Err(err) => err_counter_staged(err),
        }
    }

    /// U7 staged-transition slice: drains the observation log (FIFO,
    /// newline-joined JSON lines) into `value`.
    pub fn staged_drain_log(&self) -> EchoCounterResult {
        match self.inner.staged_drain_log() {
            Ok(log) => ok_counter(log),
            Err(err) => err_counter_staged(err),
        }
    }

    /// U7 staged-transition slice: carries the batch accounting JSON
    /// (`staged_total`, `dropped_not_staged`, `truncated_sweeps`, `cap`)
    /// in `value`.
    pub fn staged_counters(&self) -> EchoCounterResult {
        match self.inner.staged_counters() {
            Ok(counters) => ok_counter(counters),
            Err(err) => err_counter_staged(err),
        }
    }

    /// U8 first-class BLE scan start: drives a REAL kernel scan admission
    /// (synthetic radio, scripted observations). The start observation JSON
    /// travels in `value` and carries the core-minted scan op id
    /// (`"op_id"`); the caller passes it to [EchoSession::ble_scan_stop].
    /// The core owns duplicate/merge/timeout admission and the deadline.
    pub fn ble_scan_start(
        &self,
        owner: String,
        timeout_ms: String,
        now_ms: String,
    ) -> EchoCounterResult {
        match self.inner.ble_scan_start(&owner, &timeout_ms, &now_ms) {
            Ok(observation) => ok_counter(observation),
            Err(err) => err_counter(err),
        }
    }

    /// U8 first-class BLE scan take: drains the session observation log
    /// (FIFO, newline-joined JSON lines; empty string when quiet) into
    /// `value`. Delivery pacing only.
    pub fn ble_scan_take(&self) -> EchoCounterResult {
        match self.inner.ble_scan_take() {
            Ok(log) => ok_counter(log),
            Err(err) => err_counter(err),
        }
    }

    /// U8 first-class BLE scan stop: stops the core scan admitted under
    /// `op_id` and carries the stop observation JSON in `value`. An
    /// unknown op id fails closed; a stop is never fabricated.
    pub fn ble_scan_stop(&self, op_id: String, now_ms: String) -> EchoCounterResult {
        match self.inner.ble_scan_stop(&op_id, &now_ms) {
            Ok(observation) => ok_counter(observation),
            Err(err) => err_counter(err),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const REV: &str = core_backend::CONTRACT_REVISION;

    #[test]
    fn udl_surface_round_trips() {
        let session = EchoSession::new(REV.to_string());
        let out = session.echo_bytes(vec![1, 2, 250]);
        assert!(out.ok && out.data == vec![1, 2, 250]);
        let counter = session.echo_counter("18446744073709551615".to_string());
        assert!(counter.ok && counter.value == "18446744073709551615");
        let bad = session.echo_counter("nope".to_string());
        assert!(!bad.ok && bad.code == "bytes.invalid" && bad.domain == "core");
    }

    #[test]
    fn udl_ble_scan_slice_runs_real_kernel_transitions() {
        let session = EchoSession::new(REV.to_string());
        let started = session.ble_scan_start(
            "owner-a".to_string(),
            "5000".to_string(),
            "1000".to_string(),
        );
        assert!(
            started.ok,
            "scan start must admit: {}|{} {}",
            started.code, started.domain, started.value
        );
        assert!(
            started.value.contains("\"ok\":true"),
            "unexpected start observation: {}",
            started.value
        );
        let op_id = extract_test_op_id(&started.value);
        assert!(
            !op_id.is_empty(),
            "start observation must carry op_id: {}",
            started.value
        );
        let take = session.ble_scan_take();
        assert!(take.ok, "take must drain: {}|{}", take.code, take.domain);
        let stopped = session.ble_scan_stop(op_id, "2000".to_string());
        assert!(
            stopped.ok,
            "scan stop must settle: {}|{} {}",
            stopped.code, stopped.domain, stopped.value
        );
        // A second stop for the same op id fails closed: stops are never
        // fabricated and op ids are single-use.
        let again = session.ble_scan_stop("no-such-op".to_string(), "3000".to_string());
        assert!(!again.ok && again.code == "argument.invalid" && again.domain == "core");
        // Malformed decimal times fail before the radio.
        let bad = session.ble_scan_start(
            "owner-a".to_string(),
            "nope".to_string(),
            "1000".to_string(),
        );
        assert!(!bad.ok && bad.code == "bytes.invalid" && bad.domain == "core");
        // Lifetime gates cover the new slice too.
        let foreign = EchoSession::new("C-UBM.9.9.9-DRAFT".to_string());
        let gated = foreign.ble_scan_start("o".to_string(), "5".to_string(), "1".to_string());
        assert!(!gated.ok && gated.code == "protocol.incompatible");
        let closed = EchoSession::new(REV.to_string());
        assert!(closed.close().ok);
        let after = closed.ble_scan_take();
        assert!(!after.ok && after.code == "lifecycle.destroyed");
    }

    fn extract_test_op_id(observation: &str) -> String {
        const KEY: &str = "\"op_id\":\"";
        let start = observation
            .find(KEY)
            .map(|index| index + KEY.len())
            .unwrap_or(0);
        let end = observation[start..]
            .find('"')
            .map(|index| start + index)
            .unwrap_or(start);
        observation[start..end].to_string()
    }

    #[test]
    fn udl_surface_gates_revision_and_close() {
        let foreign = EchoSession::new("C-UBM.9.9.9-DRAFT".to_string());
        assert!(!foreign.echo_bytes(vec![1]).ok);
        assert_eq!(foreign.echo_bytes(vec![1]).code, "protocol.incompatible");
        let session = EchoSession::new(REV.to_string());
        assert!(session.close().ok);
        let after = session.echo_bytes(vec![1]);
        assert!(!after.ok && after.code == "lifecycle.destroyed");
    }

    #[test]
    fn udl_surface_cancels_chunked_work() {
        let session = EchoSession::new(REV.to_string());
        assert!(session.cancel_inflight().ok);
        let out = session.echo_bytes_chunked(vec![1, 2, 3], 10);
        assert!(!out.ok && out.code == "operation.aborted");
    }

    #[test]
    fn udl_surface_drives_staged_synthetic_steps() {
        let session = EchoSession::new(REV.to_string());
        let scan = session.staged_step(
            "{\"step\":\"scan.start\",\"op\":\"scan0\",\"owner\":\"owner-a\"}".to_string(),
        );
        assert!(scan.ok, "{}|{}|{}", scan.code, scan.domain, scan.operation);
        assert!(scan.value.contains("central.scan-start"), "{}", scan.value);
        let counters = session.staged_counters();
        assert!(counters.ok);
        assert!(
            counters.value.contains("\"dropped_not_staged\":0"),
            "{}",
            counters.value
        );
        let loud = session.staged_step("not-json".to_string());
        assert!(loud.ok);
        assert!(loud.value.contains("\"ok\":false"), "{}", loud.value);
        assert!(session.close().ok);
        let after = session.staged_step("{\"step\":\"cap.project\"}".to_string());
        assert!(!after.ok && after.code == "lifecycle.destroyed");
    }

    #[test]
    fn udl_surface_drives_the_transition_core() {
        let session = EchoSession::new(REV.to_string());
        let status = session.central_status();
        assert!(status.ok);
        assert_eq!(
            status.value,
            "{\"revision\":\"C-UBM.0.1.2-DRAFT\",\"live_operations\":0,\"retained_cleanup\":0}"
        );
        let sweep = session.drive_expire_sweep("0".to_string());
        assert!(sweep.ok && sweep.value == "0");
        let bad = session.drive_expire_sweep("nope".to_string());
        assert!(!bad.ok && bad.code == "bytes.invalid" && bad.domain == "core");
        let destroy = session.drive_destroy();
        assert!(destroy.ok && destroy.value == "released");
        assert!(session.drive_destroy().ok, "destroy drive is idempotent");
        let loud = session.request_ble_transition("scan.start".to_string());
        assert!(!loud.ok);
        assert_eq!(
            (
                loud.code.as_str(),
                loud.domain.as_str(),
                loud.operation.as_str()
            ),
            (
                "capability.unsupported",
                "capability",
                "request-ble-transition"
            )
        );
        assert!(session.close().ok);
        assert!(!session.central_status().ok);
        assert_eq!(session.central_status().code, "lifecycle.destroyed");
    }

    #[test]
    fn production_surface_has_no_panic_probe() {
        // The wiring slice deleted the test-only probe: no feasibility-only
        // method may ship on the UDL surface. The UDL text below IS the
        // whole interface, so asserting on it (not just on a live call) is
        // the real proof; the Python exchange asserts `not hasattr` live.
        const UDL: &str = include_str!("ubm_echo.udl");
        assert!(
            !UDL.contains("panic_probe"),
            "UDL must not expose panic_probe"
        );
        let session = EchoSession::new(REV.to_string());
        let out = session.echo_bytes(vec![7]);
        assert!(out.ok && out.data == vec![7]);
    }
}
