const { createEphemeralHostIdentity, normalizeBleManagerCreateOptions } = require('../src/public/host-identity')
const { resolveStreamPreset } = require('../src/public/stream-presets')
const { snapshotResourceCounters, diagnosticsUnavailable } = require('../src/public/diagnostics')
const { mergePeerDirectoryRecords } = require('../src/public/peer-directory')
const { BackendContractError } = require('../src/backend-contract/errors')
const { collectExportEntries, parseVerifiedSection } = require('../scripts/docs/check-api-reports')
const { createPublicGattDatabase } = require('../src/public/gatt')
const { runWithCleanup, BleCleanupError } = require('../src/public/error-bridge')
const { BleError } = require('../src/public/errors')
const { createNodeBleManagerFromProvider } = require('../src/node-host-manager')
const { coreBluetoothCompatibility } = require('../src/node-corebluetooth')
const { IpcBleManager } = require('../src/ipc/manager')
const { BUILT_IN_FEATURE_IDS } = require('../src/backend-contract/capabilities')

function expectCode(run, code) {
  try {
    run()
    throw new Error(`expected ${code}`)
  } catch (error) {
    expect(error).toBeInstanceOf(BackendContractError)
    expect(error.normalized.code).toBe(code)
  }
}

describe('rc.4.1 fail-closed audit closure', () => {
  test('P2-04 rejects injected randomBytes that are the wrong length or type', () => {
    expectCode(
      () => createEphemeralHostIdentity({ randomBytes: () => new Uint8Array([1, 2, 3, 4, 5, 6, 7, 8]) }),
      'argument.invalid'
    )
    expectCode(() => createEphemeralHostIdentity({ randomBytes: () => 'not-bytes' }), 'argument.invalid')
    const identity = createEphemeralHostIdentity({
      randomBytes: length => new Uint8Array(length).fill(9)
    })
    expect(identity.attachmentNonce).toHaveLength(32)
    expect(identity.operationNonce).toHaveLength(16)
  })

  test('P2-01 rejects non-record create options before Object.keys', () => {
    expectCode(() => normalizeBleManagerCreateOptions(null), 'argument.invalid')
    expectCode(() => normalizeBleManagerCreateOptions([]), 'argument.invalid')
    expectCode(() => normalizeBleManagerCreateOptions({ diagnostics: null }), 'argument.invalid')
  })

  test('P2-05 maps unknown and incomplete custom stream presets to argument.invalid', () => {
    expectCode(() => resolveStreamPreset({ preset: 'custom' }), 'argument.invalid')
    expectCode(() => resolveStreamPreset({ preset: 'not-a-preset' }), 'argument.invalid')
  })

  test('P2-03 rejects malformed counters and uses a public capability error when diagnostics are unavailable', () => {
    expectCode(
      () => snapshotResourceCounters({ activeScanControllers: Number.NaN }),
      'protocol.violation'
    )
    expectCode(() => snapshotResourceCounters({ scanConsumers: -1 }), 'protocol.violation')
    expectCode(() => snapshotResourceCounters({ connectionLeases: 1.5 }), 'protocol.violation')
    const diagnostics = diagnosticsUnavailable()
    expectCode(() => diagnostics.snapshot(), 'capability.unavailable')
  })

  test('P2-06 uses code-unit order and rejects non-finite RSSI', () => {
    const base = {
      source: 'scan-observed',
      state: { reachability: 'unknown', connection: 'unknown', bond: 'unknown', lastSeenAtMonotonicMs: null }
    }
    const upper = {
      ...base,
      reference: { version: 1, backendId: 'unified-ble:test', scope: 'application', opaqueId: 'A-peer' },
      peer: { id: 'A-peer', name: null, rssi: -40 }
    }
    const lower = {
      ...base,
      reference: { version: 1, backendId: 'unified-ble:test', scope: 'application', opaqueId: 'a-peer' },
      peer: { id: 'a-peer', name: null, rssi: -50 }
    }
    expect(mergePeerDirectoryRecords([lower, upper]).map(peer => peer.id)).toEqual(['A-peer', 'a-peer'])
    expectCode(
      () => mergePeerDirectoryRecords([{ ...upper, peer: { ...upper.peer, rssi: Number.NaN } }]),
      'peer.reference-invalid'
    )
    expectCode(
      () => mergePeerDirectoryRecords([{ ...upper, peer: { ...upper.peer, rssi: Number.POSITIVE_INFINITY } }]),
      'peer.reference-invalid'
    )
  })

  test('RB-03 API checker treats optional-parameter drift as a signature mismatch', () => {
    const entries = collectExportEntries(['src/expo.ts']).get('src/expo.ts')
    const create = entries.find(entry => entry.name === 'createExpoBleManager')
    expect(create).toEqual(expect.objectContaining({ name: 'createExpoBleManager' }))
    expect(create.signature).toMatch(/options\?:/)
    const drifted = entries.map(entry =>
      entry.name === 'createExpoBleManager'
        ? { name: entry.name, signature: entry.signature.replace('options?:', 'options:') }
        : entry
    )
    const report = [
      '# API Report — unified-ble-manager/expo',
      '## Verified exported symbols',
      '<!-- This section is generated by scripts/docs/check-api-reports.js. -->',
      '<!-- entrypoint: ./expo; source: src/expo.ts -->',
      '',
      ...drifted.map(entry => `- \`${entry.name} :: ${entry.signature}\``),
      ''
    ].join('\n')
    expect(() => parseVerifiedSection(report, './expo', 'src/expo.ts', entries)).toThrow(/signature/)
  })

  test('RB-03 API checker records root type re-exports with interface members, not any', () => {
    const entries = collectExportEntries(['src/index.ts']).get('src/index.ts')
    const manager = entries.find(entry => entry.name === 'BleManager')
    const connection = entries.find(entry => entry.name === 'BleConnection')
    expect(manager).toEqual(expect.objectContaining({ name: 'BleManager' }))
    expect(connection).toEqual(expect.objectContaining({ name: 'BleConnection' }))
    expect(manager.signature).not.toBe('any')
    expect(connection.signature).not.toBe('any')
    expect(manager.signature).toMatch(/connect\s*(\(|:)/)
    expect(manager.signature).toMatch(/options\?:/)
    expect(connection.signature).toMatch(/controls/)
    expect(connection.signature).toMatch(/release\s*(\(|:)/)
    const drifted = entries.map(entry =>
      entry.name === 'BleManager'
        ? { name: entry.name, signature: entry.signature.replace('options?:', 'options:') }
        : entry
    )
    const report = [
      '# API Report — unified-ble-manager',
      '## Verified exported symbols',
      '<!-- This section is generated by scripts/docs/check-api-reports.js. -->',
      '<!-- entrypoint: .; source: src/index.ts -->',
      '',
      ...drifted.map(entry => `- \`${entry.name} :: ${entry.signature}\``),
      ''
    ].join('\n')
    expect(() => parseVerifiedSection(report, '.', 'src/index.ts', entries)).toThrow(/signature/)
  })

  test('P1-13 rejects unresolved included-service refs and non-boolean characteristic properties', async () => {
    const path = {
      attachment: {},
      attachmentId: 'attachment-1',
      peerId: 'peer-1',
      connectionId: 'connection-1',
      ownerLeaseId: 'lease-1',
      connectionGeneration: 'generation-1',
      databaseId: 'database-1',
      databaseGeneration: '1'
    }
    const baseService = {
      path: { ...path, serviceUuid: '1800', serviceOccurrence: '0' },
      primary: true,
      includedServices: []
    }
    const dangling = {
      path: { ...path, serviceUuid: '1801', serviceOccurrence: '0' },
      primary: true,
      includedServices: [{ uuid: '1800', occurrence: '99' }]
    }
    await expect(createPublicGattDatabase(gattSource({ path, services: [baseService, dangling], characteristics: [], descriptors: [] }))).rejects.toMatchObject({
      code: 'protocol.violation'
    })
    const malformedProperty = {
      path: {
        ...path,
        serviceUuid: '1800',
        serviceOccurrence: '0',
        characteristicUuid: '2a00',
        characteristicOccurrence: '0',
        validity: 'current'
      },
      properties: {
        read: 'yes',
        writeWithResponse: true,
        writeWithoutResponse: false,
        notify: false
      }
    }
    await expect(
      createPublicGattDatabase(
        gattSource({
          path,
          services: [baseService],
          characteristics: [malformedProperty],
          descriptors: []
        })
      )
    ).rejects.toMatchObject({ code: 'protocol.violation' })

    const optionalNonBoolean = {
      path: malformedProperty.path,
      properties: {
        read: true,
        writeWithResponse: true,
        writeWithoutResponse: false,
        notify: false,
        indicate: 'yes'
      }
    }
    await expect(
      createPublicGattDatabase(
        gattSource({
          path,
          services: [baseService],
          characteristics: [optionalNonBoolean],
          descriptors: []
        })
      )
    ).rejects.toMatchObject({ code: 'protocol.violation' })

    const malformedAvailability = {
      path: malformedProperty.path,
      properties: {
        read: true,
        writeWithResponse: true,
        writeWithoutResponse: false,
        notify: false,
        availability: { indicate: 'maybe' }
      }
    }
    await expect(
      createPublicGattDatabase(
        gattSource({
          path,
          services: [baseService],
          characteristics: [malformedAvailability],
          descriptors: []
        })
      )
    ).rejects.toMatchObject({ code: 'protocol.violation' })

    const malformedAccess = {
      path: malformedProperty.path,
      properties: {
        read: true,
        writeWithResponse: true,
        writeWithoutResponse: false,
        notify: false
      },
      access: { read: 'maybe', write: 'unknown' }
    }
    await expect(
      createPublicGattDatabase(
        gattSource({
          path,
          services: [baseService],
          characteristics: [malformedAccess],
          descriptors: []
        })
      )
    ).rejects.toMatchObject({ code: 'protocol.violation' })

    const malformedDescriptor = {
      path: {
        ...malformedProperty.path,
        descriptorUuid: '2901',
        descriptorOccurrence: '0'
      },
      properties: {
        read: 'yes',
        write: false,
        availability: { read: 'known', write: 'unknown' },
        access: { read: 'unknown', write: 'unknown' }
      }
    }
    await expect(
      createPublicGattDatabase(
        gattSource({
          path,
          services: [baseService],
          characteristics: [
            {
              path: malformedProperty.path,
              properties: {
                read: true,
                writeWithResponse: true,
                writeWithoutResponse: false,
                notify: false
              }
            }
          ],
          descriptors: [malformedDescriptor]
        })
      )
    ).rejects.toMatchObject({ code: 'protocol.violation' })
  })

  test('P1-14 Node host factories rehydrate BackendContractError to BleError', async () => {
    await expect(
      createNodeBleManagerFromProvider(
        { listAdapters: async () => [] },
        coreBluetoothCompatibility,
        { diagnostics: null }
      )
    ).rejects.toBeInstanceOf(BleError)
  })

  test('P1-10 local IPC stream overflow stops the remote scan producer', async () => {
    const commands = []
    const listeners = []
    const backendGeneration = 'backend-generation-1'
    const bootstrap = {
      attachment: {
        attachmentId: 'attachment-1',
        backendInstanceId: 'backend-1',
        backendGeneration,
        adapter: {
          adapterId: 'adapter-1',
          displayName: 'Bluetooth',
          state: {
            availability: 'available',
            authorization: 'granted',
            power: 'on',
            backendGeneration,
            updatedAt: 1,
            safeReason: null
          },
          adapterGeneration: 'adapter-generation-1',
          limitations: []
        }
      },
      attachmentId: 'attachment-1',
      versions: {
        backendContract: { axis: 'backend-contract', selected: { axis: 'backend-contract', value: 1 }, localRange: { axis: 'backend-contract', minimum: { axis: 'backend-contract', value: 1 }, maximum: { axis: 'backend-contract', value: 1 } }, remoteRange: { axis: 'backend-contract', minimum: { axis: 'backend-contract', value: 1 }, maximum: { axis: 'backend-contract', value: 1 } } },
        capabilitySchema: { axis: 'capability-schema', selected: { axis: 'capability-schema', value: 1 }, localRange: { axis: 'capability-schema', minimum: { axis: 'capability-schema', value: 1 }, maximum: { axis: 'capability-schema', value: 1 } }, remoteRange: { axis: 'capability-schema', minimum: { axis: 'capability-schema', value: 1 }, maximum: { axis: 'capability-schema', value: 1 } } },
        eventSchema: { axis: 'event-schema', selected: { axis: 'event-schema', value: 1 }, localRange: { axis: 'event-schema', minimum: { axis: 'event-schema', value: 1 }, maximum: { axis: 'event-schema', value: 1 } }, remoteRange: { axis: 'event-schema', minimum: { axis: 'event-schema', value: 1 }, maximum: { axis: 'event-schema', value: 1 } } },
        traceFormat: { axis: 'trace-format', selected: { axis: 'trace-format', value: 1 }, localRange: { axis: 'trace-format', minimum: { axis: 'trace-format', value: 1 }, maximum: { axis: 'trace-format', value: 1 } }, remoteRange: { axis: 'trace-format', minimum: { axis: 'trace-format', value: 1 }, maximum: { axis: 'trace-format', value: 1 } } },
        ipcProtocol: { axis: 'ipc-protocol', selected: { axis: 'ipc-protocol', value: 2 }, localRange: { axis: 'ipc-protocol', minimum: { axis: 'ipc-protocol', value: 2 }, maximum: { axis: 'ipc-protocol', value: 2 } }, remoteRange: { axis: 'ipc-protocol', minimum: { axis: 'ipc-protocol', value: 2 }, maximum: { axis: 'ipc-protocol', value: 2 } } }
      },
      capabilities: {
        schemaVersion: 2,
        backendGeneration,
        descriptors: Object.values(BUILT_IN_FEATURE_IDS).map(id => ({
          id,
          state: 'unsupported',
          selectedSchemaRange: {
            axis: 'capability-schema',
            minimum: { axis: 'capability-schema', value: 1 },
            maximum: { axis: 'capability-schema', value: 1 }
          },
          implementationOrigin: 'backend-native',
          tck: {
            suiteId: 'capability.catalog-v2',
            requiredScenarioIds: ['capability.truth-limits-evidence-and-binding'],
            contractRange: {
              axis: 'capability-schema',
              minimum: { axis: 'capability-schema', value: 1 },
              maximum: { axis: 'capability-schema', value: 1 }
            }
          },
          evidence: {
            receiptId: `fixture-${id}`,
            evidenceLevel: 'blocked',
            implementationVersion: 'fixture',
            sourceDigest: `fixture-${id}`,
            scenarioIds: ['capability.truth-limits-evidence-and-binding'],
            limitations: [
              { code: 'not-implemented', explanation: 'fixture', affectedGuarantee: 'support' }
            ]
          },
          limitations: [{ code: 'not-implemented', explanation: 'fixture', affectedGuarantee: 'support' }],
          limits: { availability: { maximum: 1, minimum: null, unit: 'boolean' } }
        }))
      },
      renderer: { clientId: 'client-1', windowScope: 'window', sessionScope: 'session' },
      rendererLease: { leaseId: 'lease-1', generation: 'lease-generation-1' }
    }
    const transport = {
      invoke: async request => {
        if (request.kind === 'bootstrap') return { kind: 'bootstrap', bootstrap }
        if (request.kind === 'release') return { kind: 'release', cleanup: { state: 'released', failures: [] } }
        commands.push(request.envelope.command)
        if (request.envelope.command === 'scan.start') {
          return { kind: 'route', payload: { handle: 'scan-1' } }
        }
        return { kind: 'route', payload: { state: 'released', failureCount: 0 } }
      },
      subscribe(listener) {
        listeners.push(listener)
        return () => undefined
      },
      acknowledge: async () => ({ kind: 'event.ack' })
    }
    const ipc = await IpcBleManager.create(transport)
    await ipc.scan({
      stream: { itemCapacity: 1, byteCapacity: 4096, reservedControlCapacity: 1, overflowPolicy: 'error' }
    })
    const advertisement = {
      peerId: 'peer-1',
      localName: 'sensor',
      rssi: -40,
      txPowerLevel: null,
      serviceUuids: [],
      manufacturerData: [],
      serviceData: []
    }
    listeners[0]({
      rendererLease: bootstrap.rendererLease,
      eventId: 'scan-event-1',
      streamId: 'scan-1',
      item: { kind: 'value', value: advertisement }
    })
    listeners[0]({
      rendererLease: bootstrap.rendererLease,
      eventId: 'scan-event-2',
      streamId: 'scan-1',
      item: { kind: 'value', value: { ...advertisement, peerId: 'peer-2' } }
    })
    for (let attempt = 0; attempt < 20 && !commands.includes('scan.stop'); attempt += 1) {
      await new Promise(resolve => setImmediate(resolve))
    }
    expect(commands).toContain('scan.stop')
    await ipc.destroy()
  })

  test('P2-07 runWithCleanup throws BleCleanupError that retains the exact cleanup record', async () => {
    const cleanup = {
      state: 'release-failed',
      failures: [
        {
          resourceKind: 'connection',
          error: {
            code: 'connection.lost',
            domain: 'connection',
            operation: 'rc41.cleanup',
            platform: null,
            retryability: 'never'
          }
        }
      ]
    }
    await expect(runWithCleanup(async () => 'ok', async () => cleanup)).rejects.toMatchObject({
      name: 'BleCleanupError',
      message: 'BLE cleanup failed',
      cleanup
    })
    expect(BleCleanupError).toBeDefined()
  })
})

function gattSource(snapshot) {
  return {
    path: snapshot.path,
    monotonicNow: () => 1,
    scheduleDeadline: () => ({ cancel() {} }),
    snapshot: async () => snapshot,
    read: async () => new Uint8Array(),
    write: async () => ({ terminal: { correlation: 'w', outcome: 'succeeded', cause: null }, commitState: 'confirmed' }),
    maximumWriteLength: async () => ({
      maximumWriteLength: 20,
      observedAtMonotonicMs: 1,
      mode: 'with-response'
    }),
    writeLong: async () => ({
      terminal: { correlation: 'w', outcome: 'succeeded', cause: null },
      planState: 'not-planned',
      commitState: 'not-started',
      totalBytes: 0,
      chunkSize: 0,
      totalChunks: 0,
      chunks: [],
      completedChunks: 0,
      committedBytes: 0,
      failedChunkIndex: null
    }),
    readDescriptor: async () => new Uint8Array(),
    writeDescriptor: async () => ({
      terminal: { correlation: 'w', outcome: 'succeeded', cause: null },
      commitState: 'confirmed'
    }),
    subscribe: async () => ({
      subscriptionId: 'sub',
      path: snapshot.characteristics[0]?.path,
      values: { [Symbol.asyncIterator]: () => ({ next: async () => ({ done: true, value: undefined }) }) },
      remove: async () => ({ state: 'released', failures: [] })
    })
  }
}
